######################################################################
# Automatically generated by qmake (2.01a) ? 9 20 12:02:07 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG(debug, debug|release){
	CONFIG += qt debug
	CONFIG += console
}
else{
}

# Input
SOURCES += testqtalgorithms.cpp
