######################################################################
# Automatically generated by qmake (2.01a) ? 3 2 21:04:56 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testqmultimap.cpp
