######################################################################
# Automatically generated by qmake (2.01a) ? 6 12 18:54:46 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG(debug, debug|release){
	CONFIG += qt debug
	CONFIG += console
}
else{
}

# Input
SOURCES += testqmessagebox.cpp
