######################################################################
# Automatically generated by qmake (2.01a) ? 12 27 16:52:31 2016
######################################################################

CONFIG += qtestlib
TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testqtextstream.cpp
