######################################################################
# Automatically generated by qmake (2.01a) ? 6 11 10:27:50 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testqfontmetrics.cpp
