######################################################################
# Automatically generated by qmake (2.01a) ? 3 5 02:23:42 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testqdatastream.cpp
