######################################################################
# Automatically generated by qmake (2.01a) ? 2 5 18:00:02 2016
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testqpoint.cpp
