######################################################################
# Automatically generated by qmake (2.01a) ? 1 26 09:53:20 2016
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG(debug, debug|release){
	CONFIG += qt debug
	CONFIG += console
}
else{
}

# Input
SOURCES += testqchar.cpp
