######################################################################
# Automatically generated by qmake (2.01a) ? 4 23 17:01:41 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testqrect.cpp
