######################################################################
# Automatically generated by qmake (2.01a) ? 1 21 23:58:06 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG(debug, debug|release){
	CONFIG += qt debug
	CONFIG += console
}
else{
}

# Input
SOURCES += testqimagewriter.cpp
