######################################################################
# Automatically generated by qmake (2.01a) ? 6 22 14:29:36 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG(debug, debug|release){
	CONFIG += qt debug
	CONFIG += console
}
else{
}

# Input
SOURCES += testqlist.cpp
